version: '3'
services:
  # ========================================================================
  #    Prometheus
  # ========================================================================
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    user: root # needed for the error "cannot open /prometheus/queries.active"
    networks:
      - prometheus_network
    ports:
      - 9090:9090
    volumes:
      - prometheus:/etc/prometheus
      - /data/prometheus:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  # ========================================================================
  #    Prometheus Init
  # ========================================================================
  # # this container's job is just change the user/permission of the persistent volume claim
  # prometheus-init:
  #   image: busybox
  #   container_name: prometheus-init
  #   command: ["/bin/chmod", "-R", "777", "/etc/prometheus"]
  #   volumes:
  #     - config:/etc/prometheus/
volumes:
  prometheus:
networks:
  prometheus_network:
    name: internal_network
