version: '3'
services:
  # ========================================================================
  #    Grafana
  # ========================================================================
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    networks:
      - grafana_network
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 9000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
networks:
  grafana_network:
    name: internal_network
