groups:
  - name: SystemAlerts
    rules:
      # Alert for any instance that is down for >5 minutes.
      - alert: InstanceDown 
        # "up" is a built-in metric from Prometheus that returns 
        # zero if the services were not reachable in the last scrape.
        expr: up{job="services"} < 1 
        # "for" causes Prometheus to wait for a certain duration 
        # between first encountering a new expression output vector 
        # element and counting an alert as firing for this element
        for: 5m 
        # "labels" allows specifying a set of additional labels to 
        # be attached to the alert
        labels:
          severity: high
        # "annotations" specifies a set of informational labels that 
        # can be used to store longer additional information such as 
        # alert descriptions or runbook links
        annotations:
          summary: "instance {{ $labels.instance }} is down!"
